---
# roles/rke2_servers/vars/secrets.yml
# Secrets file. Encrypt with Ansible Vault!

rke2_config_token: YOUR-TOKEN #replace with your token
local_user: SVC-ACCOUNT   #replace with your service account
