---
# roles/rke2_servers/handlers/main.yml
# Handling all services.

- name: restart-firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: true

- name: restart-kmods
  ansible.builtin.service:
    name: systemd-modules-load
    state: restarted
    enabled: true

- name: restart-networkmanager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
    enabled: true

- name: restart-rke2-server
  ansible.builtin.service:
    name: rke2-server
    state: restarted
    enabled: true

- name: restart-rke2-agent
  ansible.builtin.service:
    name: rke2-agent
    state: restarted
    enabled: true
